name = "backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"

kv_namespaces = [
    {binding = "DASHBOARD_SETTINGS", id = "1341b22f2b2c414a9a664b25e73c072c", preview_id = "1341b22f2b2c414a9a664b25e73c072c" },
    {binding = "SESSION_STORAGE", id = "73976bf5ffb947ae86618f57db0feab1", preview_id = "73976bf5ffb947ae86618f57db0feab1" }
]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "DASHBOARD_SETTINGS"
# id = "1341b22f2b2c414a9a664b25e73c072c"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"