name = "backend"
main = "index.ts"
compatibility_date = "2023-12-01"
node_compat = true

kv_namespaces = [
    { binding = "PRODUCT_SETTINGS", id = "da9d23667f0f4d9db1197e45adcec388" },
    { binding = "SESSION_STORAGE", id = "edc19c0c8e18414bb05a9bf370a02140" },
    { binding = "DASHBOARD_SETTINGS", id = "cc46f1565a874ce3943c7f37c2709848" },
]

[[d1_databases]]
binding = "DB"
database_name = "form_submissions_db"
database_id = "0d8de1e8-429a-485c-a17c-2164f94e141d"

[triggers]
# Schedule cron triggers:
# - At every 6th hour
crons = ["* */6 * * *"]
# crons = ["0 */12 * * *"]


#compatibility_flags = [ "nodejs_compat" ]
# [vars]
# MY_VAR = "my-variable"

 
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

